### ISSUE TITLE
Formulário de login e Google Meet

### ISSUE THREAD

**Issue by JunioTk2** [Escola-em-Casa/android-escola-em-casa#13]
Olá!

Não estou familiarizado com o Github, então não sei se aqui é o local mais adequado para essas observações.

1ª - o Google forms funciona perfeitamente agora.

2ª - há alguma forma de usar o Google Meet com os dados patrocinados? Porque sempre que clico num link do Meet, ele abre o app instalado direto no celular. (aí acredito eu que não usa a vpn do projeto, certo?)

3ª - observei que a tela de login já vem pré preenchida com o perfil @edu.se.df.gov.br.
Não sei qual o planejamento aí, mas o caso é que há 3 perfis de login.
@estudante.se.df.gov.br

E os professores usam dois: @se.df..... e claro o @edu.se.df...

![Screenshot_2020-06-28-15-52-53-929_org cordova quasar corona app](https://user-images.githubusercontent.com/67401188/85955966-979b0100-b958-11ea-9b77-2d5f931070c3.jpg)

**Comment by RochaCarla** [comment]
Valeu @JunioTk2 pela tua contribuição! é por aqui mesmo :P estamos reproduzindo os comportamentos que vc levantou e vamos resolver as questões.

Somente o meet que não está no nosso escopo inicial.

**Comment by guilacerda** [comment]
@JunioTk2, muito obrigado pelo feedback! 

Sobre o terceiro ponto, já estamos em fase de teste para permitir somente a utilização de emails com os domínios citados.

**Comment by guilacerda** [comment]
@JunioTk2 foi finalizado essa issue e só é possível fazer login com os emails listados. Estarei fechando, caso haja alguma outra duvida só entrar em contato novamente.
