### ISSUE TITLE
Upload de arquivos

### ISSUE THREAD

**Issue by guilacerda** [Escola-em-Casa/android-escola-em-casa#20]
**Descrição do erro encontrado:**
O aplicativo não permite o upload de arquivos para o google classroom.

**Passo a passo para a reprodução do erro:**
Especificações do passo a passo para a reprodução do erro encontrado
1. Não é possível fazer o upload de qualquer arquivo dentro do Google Classroom em qualquer  

**Comportamento esperado:** Ser possível fazer upload de arquivos dentro do aplicativo.

**Comment by guilacerda** [comment]
@joaaogui essa issue foi finalizada?

**Comment by joaaogui** [comment]
@guilacerda Foi!
