### ISSUE TITLE
Criar a página "Dúvidas Frequentes"

### ISSUE THREAD

**Issue by guilacerda** [Escola-em-Casa/android-escola-em-casa#24]
**Descrição**

Muitos usuários estão tendo dúvidas sobre a utilização da plataforma. Criar uma página com algumas dúvidas mais frequentas, estilo FAQ.

**Tarefas**
- [x] Adicionar um novo item na navigationbar
- [x] Fazer o levantamento do conteúdo com as dúvidas mais frequentes
- [x] Desenvolver a página Dúvidas

**Comment by guilacerda** [comment]
A página e o item ao navigation bar já foram criados e adicionados. Agora está faltando somente fazer o levantamento do conteúdo com as dúvidas mais frequentes entre os professores e alunos.

**Comment by miguelpimentel** [comment]
@guilacerda tudo bom? teria algum contato para pegar as issues em aberto e já começar a ajudar o quantos antes? Encontrei algumas coisas arquiteturais/problemas.

**Comment by guilacerda** [comment]
Claro! Em relação às issues, vamos começar a estruturar melhor os repositórios e deixar mais visível em que estamos trabalhando e o que está faltando. Para ter um planejamento mais alinhado com todos da comunidade :)
