### ISSUE TITLE
Abrir formularios do google

### ISSUE THREAD

**Issue by RochaCarla** [Escola-em-Casa/android-escola-em-casa#50]
O app nao abre os formulários do google, onde boa parte dos professores criam as atividades. 
Isso força o aluno a abrir a aula no navegador.

**Comment by rafaelflarrn** [comment]
Essa funcionalidade já está habilitada no app. Ao estudar o código, foi encontrada a implementação dessa funcionalidade através do WebView. Tanto o link normal quanto o link curto estão nas lista de URLs permitidas. Mais informações sobre o estudo dessa issue podem ser acessadas [aqui](https://github.com/GCES-Escola-em-Casa-2020-2/wiki/issues/9).
![forms](https://user-images.githubusercontent.com/37155530/110700599-e6c75000-81ce-11eb-9c96-53eba244970b.png)

**Comment by pedroeagle** [comment]
Testamos hoje novamente em outra conta e depende muito da forma como o formulário foi inserido para que funcione. Links encurtados por exemplo não são abertos.
