### ISSUE TITLE
Google formulários com erro de redirecionamento

### ISSUE THREAD

**Issue by JunioTk2** [Escola-em-Casa/android-escola-em-casa#8]
Ao clicar em um Google formulários, ele identifica como um vídeo do YouTube, tenta abrir e redireciona para um erro.

![Screenshot_2020-06-24-23-15-45-540_com miui gallery](https://user-images.githubusercontent.com/67401188/85645642-b48db680-b670-11ea-87c6-8448aabbd87b.jpg)
![Screenshot_2020-06-24-23-15-50-799_com miui gallery](https://user-images.githubusercontent.com/67401188/85645646-b6577a00-b670-11ea-9007-7fe69b88ebaf.jpg)
![Screenshot_2020-06-24-23-16-01-323_com miui gallery](https://user-images.githubusercontent.com/67401188/85645648-b6f01080-b670-11ea-8f4c-754447c3ae34.jpg)

**Comment by laercios** [comment]
Olá, @JunioTk2 tudo bem? 

Estamos estudando o que pode estar ocasionando esse bug. Poderia informar os seguinte dados para ajudar a gente a replicar esse bug?

- Fabricante;
- Modelo;
- Versão do android; (Você consegue ver nas configurações, tocando sobre a opção "Sobre o telefone")
- Link para formulário que está ocorrendo o erro.

Não vamos preencher o formulário vamos apenas abrir ele no aplicativo para replicar esse erro.

Agradeço muito o seu report !

**Comment by JunioTk2** [comment]
Olá @laercios !

Trata-se de um Xiaomi - mi 9 no Android 10 com último patch, como nas prints.

O erro aconteceu em vários formulários (na verdade todos que tentei clicar.)
A URL nem mesmo está encurtada.

Abaixo:

https://docs.google.com/forms/d/e/1FAIpQLSfVM1fV_VuKT6ZMaqCMkMupaDF3fn5CObdBFmob6hiRARqBdQ/viewform?hr_submission=ChkIue2ki9oCEhAIuMKIn_wDEgcIup_WnKADEAE&authuser=3


![Screenshot_2020-06-25-21-17-20-950_com android chrome](https://user-images.githubusercontent.com/67401188/85807908-b5ceea00-b729-11ea-958e-ffa9111ce2a5.jpg)
![Screenshot_2020-06-25-21-18-45-092_com android settings](https://user-images.githubusercontent.com/67401188/85807911-b798ad80-b729-11ea-9eca-3ba335028b5e.jpg)

**Comment by guilacerda** [comment]
@JunioTk2 muito obrigado por relatar essa bug. Já consertamos o problema e está sendo acoplado na nossa próxima versão. A solução técnica encontra-se no PR #12. Caso venha acontecer algum outro problema, por favor, nos comunique =D
